spring:
  application:
    name: school-scheduling-system

  datasource:
    url: jdbc:mysql://localhost:3306/school_scheduling?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  security:
    jwt:
      secret: mySecretKeyForSchoolSchedulingSystem2024
      expiration: 86400000 # 24 hours in milliseconds

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8080

logging:
  level:
    com.example.schoolscheduling: DEBUG
    org.springframework.security: DEBUG