spring:
  application:
    name: scheduling-system

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/school_scheduling?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.school.scheduling.domain
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      lazy-loading-enabled: true
      multiple-result-sets-enabled: true
      use-column-label: true
      use-generated-keys: false
      auto-mapping-behavior: partial
      default-statement-timeout: 25000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.school.scheduling: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/scheduling-system.log
    max-size: 10MB
    max-history: 30

app:
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345678901234567890}
      expiration: 86400000 # 24 hours

  scheduling:
    batch-size: 100
    max-concurrent-requests: 10

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  logging:
    level:
      com.school.scheduling: INFO
      org.springframework.web: INFO
      org.springframework.security: INFO